# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_qcprot', [dirname(__file__)])
        except ImportError:
            import _qcprot
            return _qcprot
        if fp is not None:
            try:
                _mod = imp.load_module('_qcprot', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _qcprot = swig_import_helper()
    del swig_import_helper
else:
    import _qcprot
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def MakeDMatrix(i, j):
    return _qcprot.MakeDMatrix(i, j)
MakeDMatrix = _qcprot.MakeDMatrix

def FreeDMatrix(a):
    return _qcprot.FreeDMatrix(a)
FreeDMatrix = _qcprot.FreeDMatrix

def FreeDArray(a):
    return _qcprot.FreeDArray(a)
FreeDArray = _qcprot.FreeDArray

def GetDArray(i, j, a):
    return _qcprot.GetDArray(i, j, a)
GetDArray = _qcprot.GetDArray

def SetDArray(i, j, a, v):
    return _qcprot.SetDArray(i, j, a, v)
SetDArray = _qcprot.SetDArray

def GetDvector(i, a):
    return _qcprot.GetDvector(i, a)
GetDvector = _qcprot.GetDvector

def SetDvector(i, a, v):
    return _qcprot.SetDvector(i, a, v)
SetDvector = _qcprot.SetDvector

def MakeDvector(n):
    return _qcprot.MakeDvector(n)
MakeDvector = _qcprot.MakeDvector

def MakeIvector(n):
    return _qcprot.MakeIvector(n)
MakeIvector = _qcprot.MakeIvector

def GetIvector(i, a):
    return _qcprot.GetIvector(i, a)
GetIvector = _qcprot.GetIvector

def SetIvector(i, a, v):
    return _qcprot.SetIvector(i, a, v)
SetIvector = _qcprot.SetIvector

def CalcRMSDRotationalMatrix(coords1, coords2, len, rot_matrix):
    return _qcprot.CalcRMSDRotationalMatrix(coords1, coords2, len, rot_matrix)
CalcRMSDRotationalMatrix = _qcprot.CalcRMSDRotationalMatrix

def FastCalcRMSDAndRotation(rot, A, rmsd, E0, len, minScore):
    return _qcprot.FastCalcRMSDAndRotation(rot, A, rmsd, E0, len, minScore)
FastCalcRMSDAndRotation = _qcprot.FastCalcRMSDAndRotation
# This file is compatible with both classic and new-style classes.


